# Generated by Django 4.2 on 2024-11-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='preview')),
                ('desc', models.TextField(verbose_name='description')),
                ('url', models.URLField(verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='preview')),
                ('desc', models.TextField(verbose_name='description')),
            ],
        ),
    ]
